name: Weekly Mozilla CA Subset Sync Check

on:
  schedule:
    # 06:54 every Monday (UTC)
    - cron: '54 6 * * 1'
  workflow_dispatch:

jobs:
  check-certs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run CA Comparison Script
        run: |
          ./cacomp.sh

      - name: Notify on failure
        if: failure()
        run: echo "Discrepancy found or script failed. Check logs."
